version: '3.3'
services:
   db:
     image: oscarfonts/h2:latest
     environment:
         - H2_OPTIONS=-ifNotExists
   storeWebService:
     depends_on:
       - db
     image: javacream/org.javacream.training.store.service:1.0
   booksWebService:
     depends_on:
       - db
       - storeWebService
     image: javacream/org.javacream.training.books.service:latest
   orderWebService:
     depends_on:
       - db
       - storeWebService
       - booksWebService
     image: javacream/org.javacream.training.order.web:latest
     ports:
       - "8893:9091"